function payload=export_ibr_smib_events_oracle(output_file,source_root)
%EXPORT_IBR_SMIB_EVENTS_ORACLE Export fault and grid-step SMIB trajectories.
if nargin<1 || isempty(output_file),error('export_ibr_smib_events_oracle:output','Output required.');end
if ~is_absolute_path(output_file),output_file=fullfile(pwd,output_file);end
if nargin<2 || isempty(source_root)
    here=fileparts(mfilename('fullpath'));
    source_root=fullfile(fileparts(fileparts(fileparts(here))),'Power-flow');
end
old_dir=pwd;cleanup=onCleanup(@()cd(old_dir)); %#ok<NASGU>
cd(source_root);pf_init_paths();
[~,commit]=system(sprintf('git -C "%s" rev-parse HEAD',source_root));
[~,git_status]=system(sprintf('git -C "%s" status --short',source_root));
loaders={@cases.case_ibr_smib_gfl_reduced6,@cases.case_ibr_smib_gfm_reduced6, ...
    @cases.case_ibr_smib_gfl_rms10,@cases.case_ibr_smib_gfm_no_pll, ...
    @cases.case_ibr_smib_gfm_vsm_sakimoto};
ids={'gfl_reduced6_smib','gfm_reduced6_smib','gfl_rms10_smib', ...
    'gfm_no_pll_smib','gfm_vsm_sakimoto_smib'};
items=cell(numel(loaders),1);
for k=1:numel(loaders)
    c=loaders{k}();
    opt=struct('ibr_analysis','full','t_end',0.03,'dt',0.001, ...
        'plot_results',false,'plot_visible',false,'verbose',false, ...
        'smib_fault_on',0.01,'smib_fault_clear',0.02,'smib_fault_Zf',0.10i, ...
        'smib_step_on',0.01,'smib_step_dV',-0.02,'smib_step_dphase_deg',2.0);
    r=ibr.run_smib_verification_case(c,opt); t=r.ts;
    items{k}=struct('case_id',ids{k},'kind',c.smib_verification.kind, ...
        'state_names',{t.state_names},'t',t.tgrid(:).', ...
        'fault_on',t.fault_on,'fault_clear',t.fault_clear, ...
        'fault_Zf_real',real(t.fault_Zf),'fault_Zf_imag',imag(t.fault_Zf), ...
        'fault_enabled',t.fault_enabled,'x_fault',t.x_fault.','y_fault',t.y_fault.', ...
        'fault_newton_residual',t.newton_info_fault.max_resid_history(:).', ...
        'step_on',t.step_on,'step_dV',t.step_dV, ...
        'step_dphase_deg',t.step_dphase_deg,'step_enabled',t.step_enabled, ...
        'x_step',t.x_step.','y_step',t.y_step.', ...
        'step_newton_residual',t.newton_info_step.max_resid_history(:).');
end
payload=struct('schema','power-flow-py/matlab-ibr-smib-events-oracle/1.0', ...
    'source_git_commit',strtrim(commit),'source_git_status',git_status, ...
    'classification','ASSUMED_DIAGNOSTIC_SOURCE_FROZEN_FIXTURE', ...
    'cases',[items{:}]);
parent=fileparts(output_file);if ~exist(parent,'dir'),mkdir(parent);end
fid=fopen(output_file,'w');if fid<0,error('export_ibr_smib_events_oracle:open','Open failed.');end
file_cleanup=onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s',jsonencode(payload,'PrettyPrint',true));
fprintf('Wrote IBR SMIB event oracle: %s\n',output_file);
end

function tf=is_absolute_path(path_text)
if ispc
    tf=~isempty(regexp(path_text,'^[A-Za-z]:[\\/]','once')) || startsWith(path_text,'\\\\');
else
    tf=startsWith(path_text,'/');
end
end
