function payload=export_ibr_two_switch_oracle(output_file,source_root)
%EXPORT_IBR_TWO_SWITCH_ORACLE Export default two-IBR AGSI++ switching evidence.
if nargin<1 || isempty(output_file),error('export_ibr_two_switch_oracle:output','Output required.');end
if ~is_absolute_path(output_file),output_file=fullfile(pwd,output_file);end
if nargin<2 || isempty(source_root)
    here=fileparts(mfilename('fullpath'));
    source_root=fullfile(fileparts(fileparts(fileparts(here))),'Power-flow');
end
old_dir=pwd;cleanup=onCleanup(@()cd(old_dir)); %#ok<NASGU>
cd(source_root);pf_init_paths();
[~,commit]=system(sprintf('git -C "%s" rev-parse HEAD',source_root));
[~,git_status]=system(sprintf('git -C "%s" status --short',source_root));
c=cases.case_ibr_two_ibr_switch();
r=ibr.run_two_ibr_switch_case(c,struct('plot_results',false)); t=r.tds;
sample_index=unique([1:100:numel(t.tgrid),numel(t.tgrid)]);
payload=struct('schema','power-flow-py/matlab-ibr-two-switch-oracle/1.0', ...
    'source_git_commit',strtrim(commit),'source_git_status',git_status, ...
    'classification','ASSUMED_DIAGNOSTIC_SOURCE_FROZEN_FIXTURE', ...
    'case_id','two_ibr_switch','sample_index_zero',sample_index-1, ...
    'time',t.tgrid(sample_index).','X1',t.X1(:,sample_index).', ...
    'X2',t.X2(:,sample_index).','Y',t.Y(:,sample_index).', ...
    'frequency1',t.f1(sample_index).','frequency2',t.f2(sample_index).', ...
    'index1',t.index1(sample_index).','index2',t.index2(sample_index).', ...
    'mode1',t.mode1(sample_index).','mode2',t.mode2(sample_index).', ...
    'P1',t.P1(sample_index).','P2',t.P2(sample_index).', ...
    'Q1',t.Q1(sample_index).','Q2',t.Q2(sample_index).', ...
    'switch_events',t.switch_events,'newton_all_converged',t.newton_all_converged, ...
    'dev1_n_switch',t.dev1_n_switch,'dev2_n_switch',t.dev2_n_switch, ...
    'dev1_mode',char(t.dev1_mode),'dev2_mode',char(t.dev2_mode), ...
    'peak_agsi',max(t.index1),'max_final_residual',max(t.max_resid_history));
parent=fileparts(output_file);if ~exist(parent,'dir'),mkdir(parent);end
fid=fopen(output_file,'w');if fid<0,error('export_ibr_two_switch_oracle:open','Open failed.');end
file_cleanup=onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s',jsonencode(payload,'PrettyPrint',true));
fprintf('Wrote two-IBR switch oracle: %s\n',output_file);
end

function tf=is_absolute_path(path_text)
if ispc
    tf=~isempty(regexp(path_text,'^[A-Za-z]:[\\/]','once')) || startsWith(path_text,'\\\\');
else
    tf=startsWith(path_text,'/');
end
end
